---
title: "Simulation Code"
output: html_document
date: '2023-10-02'
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Packages}
library(dplyr)

# "fixest" for fast estimation of fixed effects models
library(fixest)
setFixest_nthreads(1, save = FALSE)
getFixest_nthreads()
```

```{r Functions}
# function for partitioning
partitionf <- function(df, cut_point){
  df2 <- df %>%
    group_by(indiv, .data[[cut_point]]) %>%
    mutate(
      rownum = 1:n(),
      eventI = ifelse(event>0, 1, 0) # greater than one
    )
  firstevent_index <- df2 %>% 
    summarise(
      rownum = which(eventI==1)[1]#, # index of the first >0 eve t
    ) %>% suppressMessages()
  firstevent_index[,paste0("eventnum1_", cut_point)] <- ifelse(!is.na(firstevent_index$rownum), 1, 0)

  
  df3 <- merge(df2, firstevent_index,  by=c("indiv",cut_point,"rownum"), all.x= TRUE) %>%
    arrange(indiv, intstart)
  df3[,paste0("eventnum1_", cut_point)] <- ifelse(is.na(df3[,paste0("eventnum1_", cut_point)]), 0, df3[,paste0("eventnum1_", cut_point)])
  df3
  return(df3)
}

# function for probability of event
pev <- function(lambda, nevent, result){
  (exp(-lambda)*(lambda^nevent)/(factorial(nevent)*(1-exp(-lambda))))-result
}
```

```{r Import simulation guide}
SimScenarios <- read.csv("SimScenarios.csv")
SimScenarios

# set active scenario
# select the corresponding scenario number from min(SimScenarios$X):max(SimScenarios$X) 
ScenarioNumber <- 1 
ActiveScenario <- SimScenarios %>% filter(sim_scenario_n == ScenarioNumber)
```

```{r Simulation code}
# Create export df
conditions <- c("cond_baseline2_E.events", "cond_RIexpo","cond_eventdependence","cond_exposdist","cond_season")
save <- c("allevent", "firstevent", "OT_adj_2", "OT_adj_guide", "combinedpartition_fixed_2", "combinedpartition_guide")
savenames <- c("scenario", conditions, save, paste0("iidse_", save[1:4]), paste0("clusterse_", save[5:6]))
savenames
results <- data.frame(matrix(ncol = length(savenames), nrow = 0))
colnames(results) <- c("scenario", conditions, save, paste0("iidse_", save[1:4]), paste0("clusterse_", save[5:6]))
results
results[c("cond_eventdependence","cond_exposdist","cond_season")] <- sapply(results[c("cond_eventdependence","cond_exposdist","cond_season")], as.character) # convert character columns to character columns

if(ActiveScenario$list_exposdist != "Seasonal"){
  ntime = 100
  expo_length = 10
  season <- "n"
}else if (ActiveScenario$list_exposdist != "Seasonal"){
  ntime = 730
  expo_length = 14
  # exposdist <- "Seasonal"
  # list_exposdist <- c("Seasonal")
  season <- "y"
  # RIseason <- 1
  RIseason <- 2
}


nindiv = 1000 # same as Whitaker et al. (2018)
baseline1 <- 0.05/ntime # E[event] = 0.05

# n_sims <- 2000
n_sims <- 5

set.seed(ActiveScenario$seed)

start.time <- Sys.time()
for(baseline2 in ActiveScenario$list_baseline2){
  for(RIexpo in ActiveScenario$list_RIexpo){
    for(eventdependence in ActiveScenario$list_eventdependence){
      for(exposdist in ActiveScenario$list_exposdist){
        for(f in 1:n_sims){
          
          #-----DGP [START]-----
          
          cases_wide <- data.frame()
          cases <- data.frame()
          
          ncases <- 0
          
          #-----CREATE DATA [START]-----
          # 1. create individuals in wide-format until we have ncases
          while(ncases < nindiv){
            
            # exposure start
            expo_temp <- ifelse( # if random uniform
              exposdist == "Uniform",
              sample(1:(ntime-expo_length), 1, replace=T),
              ifelse( # if random Early
                exposdist == "Early",
                # round(EnvStats::rtri(n=1, min=0, max=ntime-expo_length, mode = 0.5)),
                rbeta(1, shape1=1, shape2=3)*(ntime-expo_length), # rbeta(1000, shape1=1, shape2=3) %>% density() %>% plot()
                ifelse( # if random late
                  exposdist == "Late",
                  # round(EnvStats::rtri(n=1, min=0, max=ntime-expo_length, mode = ntime-expo_length-0.5)),
                  rbeta(1, shape1=3, shape2=1)*(ntime-expo_length), # rbeta(1000, shape1=3, shape2=1) %>% density() %>% plot()
                  "" # don't do anything
                )
              )
            )
            if(exposdist == "Seasonal"){
              expo_temp <- t(c(sample(245:(365-expo_length), 1, replace=T), sample(610:(730-expo_length), 1, replace=T)))
            }
            
            # create individual
            if(season=="y"){
              season_temp <- t(c(0, 333, 698))
              season_length <- t(c(60, 92, 32))
              
              temp <- data.frame(
                obsstart = 0, obsend=ntime, 
                expostart = expo_temp, expoend = expo_temp+expo_length, 
                seasonstart = season_temp, seasonend = season_temp+season_length)
              
            }else if(season=="n"){
              temp <- data.frame(obsstart = 0, obsend=ntime, expostart = expo_temp, expoend = expo_temp+expo_length)
            }
            temp <- temp[,order(t(temp))] %>% 
              # move obsend to last (in case expoend = obsend)
              relocate(obsend, .after = last_col())
            temp
            
            eventcounter=0
            
            #-----GENERATE EVENTS [START]-----
            
            # set temp individual's baseline rate
            baseline_sample <- rbinom(1, 1, 0.05)
            # if baseline_sample is 1 (with 95% chance), then use baseline 1, else baseline2
            baseline <- ifelse(baseline_sample==0, baseline1, baseline2)
            
            # for each column (interval)
            intervals <- ncol(temp)-1
            for(i in 1:intervals){
              
              # set lambda depending on interval
              # 1. we set lambda for each interval based on exposure
              if(exposdist != "Seasonal"){
                lambda <- ifelse(
                  # in exposure period
                  i >= which(colnames(temp)=="expostart") & i < which(colnames(temp)=="expoend"),
                  baseline*RIexpo,
                  # outside exposure period
                  baseline
                )
              }else if(exposdist == "Seasonal"){
                x = 1:length(expo_temp)
                lambda <- ifelse(
                  # if there is one entry of vector x where the given statement is TRUE
                  TRUE %in% (
                    i >= which(colnames(temp) %in% paste0("expostart.",x)) & i < which(colnames(temp) %in% paste0("expoend.",x))
                  ),
                  baseline*RIexpo,
                  baseline
                )
              }
              
              # 2. we alter lambda using the seasonal effect
              if(season=="y"){
                # lambda2 <- lambda
                
                # 8/8/2022 THIS ONE IS GOOD?
                x = 1:length(season_temp)
                lambda <- ifelse(
                  # if there is one entry of vector x where the given statement is TRUE
                  TRUE %in% (i >= which(colnames(temp) %in% paste0("seasonstart.",x)) & i < which(colnames(temp) %in% paste0("seasonend.",x))),
                  lambda*RIseason,
                  lambda
                )
              }
              
              
              # set interval remaining time
              tremain <- temp[,i+1]-temp[,i] # this should hold up, but I'm worried with too many cutpoints, may be an issue? (but may not be a problem with memoryless? unsure)
              
              
              # while there is still time remaining
              while(tremain > 0){
                
                # simulate event time w/ inverse exponential CDF
                # uniform distribution sampling
                u <- runif(n=1, min=0, max=1)
                # event dependence
                if(eventdependence == "n"){
                  eventdep <- 1
                }else if(eventdependence == "y"){
                  eventdep <- exp(1*log(eventcounter+1))
                }
                # event time
                t <- -log(1-u)/(lambda*eventdep)
                
                
                
                # print(paste("time =",t))
                
                # if event time is less than the remaining time
                if(t < tremain){
                  # add event to event counter
                  eventcounter = eventcounter + 1
                  # new remaining time
                  tremain = tremain - t
                  
                  # print(paste("remaining time =",tremain))
                  
                  # add column with event time
                  temp[,paste0("tevent", eventcounter)] = temp[,i+1] - tremain
                  
                  # if event time is greater than remaining time
                }else{
                  # end the while loop
                  # tremain = tremain - t
                  tremain = 0
                }
              }
            }
            #-----GENERATE EVENTS [END]-----
            
            temp$nevent <- eventcounter
            temp$baseline <- baseline_sample # p(0) = 0.95, p(1) = 0.05
            temp$indiv <- ncases+1
            temp <- temp %>% select(indiv, nevent, everything())
            
            # cases <- dplyr::bind_rows(cases, temp)
            
            # only keep cases
            if(temp$nevent > 0){
              cases_wide <- dplyr::bind_rows(cases_wide, temp)
              # for the while loop
              ncases <- ncases+1
              # print(ncases)
            }
          }
          
          # 2. convert data from wide-format to long-format
          
          # add cut points to cases_wide
          
          ## Recommended cutpoints
          case_dist <- data.frame(table(cases_wide$nevent)/1000)
          est_cumul_inc <- uniroot(pev, nevent=as.numeric(case_dist$Var1[1]), result=as.numeric(case_dist$Freq[1]), lower=-100, upper=100)$root
          # est_cumul_inc <- uniroot(momest, avg=sum(as.numeric(case_dist$Var1) * case_dist$Freq), lower=-100, upper=100)$root
          cutpoint_guide_num <- round(est_cumul_inc/0.1)
          cutpoint_guide <- t(seq(from = 0+ntime/cutpoint_guide_num, to = ntime-ntime/cutpoint_guide_num, by = ntime/cutpoint_guide_num))
          
          ## fixed cutpoints
          cutpoint_fixed_2 <- t(seq(from = 0+ntime/2, to = ntime-ntime/2, by = ntime/2))
          cutpoint_fixed_4 <- t(seq(from = 0+ntime/4, to = ntime-ntime/4, by = ntime/4))
          cutpoint_fixed_6 <- t(seq(from = 0+ntime/6, to = ntime-ntime/6, by = ntime/6))
          
          ## 1 random cutpoint
          cutpoint_random_2 <- replicate(nindiv, sort(sample(1:(ntime-expo_length), 1, replace=T)))
          
          ## add cutpoints
          # cases_wide <- cases_wide %>% select(-contains("tcut"))
          cases_wide <- data.frame(cases_wide, tcut_fixed_2 = cutpoint_fixed_2, tcut_fixed_4 = cutpoint_fixed_4, tcut_fixed_6 = cutpoint_fixed_6, tcut_random_2 = cutpoint_random_2, tcut_guide = cutpoint_guide) 
          cases_wide # export this cases_wide later - can be fed in at this point to generate the rest of the results if need
          
          # convert cases to long form
          cases_long <- cases_wide %>%
            tidyr::pivot_longer(names_to="int", values_to="intstart", cols=-c(indiv, nevent, baseline, contains("tevent"))) %>% 
            group_by(indiv) %>%
            # sort by each individual and intstart
            arrange(indiv, intstart) %>%
            # create new columns for interval length and exposure dummy
            mutate(
              intstart_lag = dplyr::lag(intstart, default=0),
              intlength = intstart - intstart_lag#,
              # expos = ifelse(int=="expoend", 1, 0)
              # expos = ifelse(grepl("expoend", int), 1, 0)
            ) %>%  
            # reorder so tevent is at end
            select(-contains("tevent"), contains("tevent"))
          
          # merge (tcuts, texposstart, texposend, tseasonstart, tseasonend) columns to long data to indiv
          if(season == "y"){
            cases_timing <- cases_wide %>% select(indiv, contains("cut"), contains("expo"), contains("season"))
          }else{
            cases_timing <- cases_wide %>% select(indiv, contains("cut"), contains("expo"))
          }
          
          cases_long <- merge(cases_long, cases_timing, by="indiv") %>%  
            # reorder so tevent is at end
            select(-contains("tevent"), contains("tevent"))
          
          # eventnum's for each event corresponding to the correct interval
          for(i in 1:max(cases_long$nevent)){
            cases_long[,paste0("eventnum",i)] <- ifelse(cases_long$intstart_lag < cases_long[,paste0("tevent",i)] & cases_long[,paste0("tevent",i)] < cases_long$intstart, 1, 0)
          }
          
          # create dummy variables for exposure (and seasons)
          cases_long$expos <- 0
          for(i in 1:length(expo_temp)){
            I <- ifelse(length(expo_temp)==1, "", paste0(".",i))
            # add dummies from expos periods
            cases_long$expos <- cases_long$expos + ifelse(cases_long$intstart > cases_long[,paste0("expostart",I)] & cases_long$intstart <= cases_long[,paste0("expoend",I)], 1, 0)
          }
          cases_long %>% select(indiv, int, intstart, intlength, expos)
          
          # create dummy variables for seasons
          cases_long$season <- 0
          if(season=="y"){
            for(i in 1:length(season_temp)){
              I <- ifelse(length(season_temp)==1, "", paste0(".",i))
              # add dummies from expos periods
              cases_long$season <- cases_long$season + ifelse(cases_long$intstart > cases_long[,paste0("seasonstart",I)] & cases_long$intstart <= cases_long[,paste0("seasonend",I)], 1, 0)
            }
          }
          # cases_long %>% select(indiv, int, intstart, intlength, season)
          
          # create a cut dummy variable corresponding to correct interval
          cases_long$cut_fixed_2 <- ifelse(cases_long$intstart_lag < cases_long$tcut_fixed_2, 0, 1)
          cases_long$cut_random_2 <- ifelse(cases_long$intstart_lag < cases_long$tcut_random_2, 0, 1)
          for(i in 1:3){
            # if there is only 1 cut, then it's only "tcut_fixed", if there are n cuts, its "tcut_fixed.n"
            I <- paste0(".",i)
            cases_long[,paste0("cut_fixed_4",I)] <- ifelse(cases_long$intstart_lag < cases_long[,paste0("tcut_fixed_4",I)], 0, 1)
          }
          for(i in 1:5){
            # if there is only 1 cut, then it's only "tcut_fixed", if there are n cuts, its "tcut_fixed.n"
            I <- paste0(".",i)
            cases_long[,paste0("cut_fixed_6",I)] <- ifelse(cases_long$intstart_lag < cases_long[,paste0("tcut_fixed_6",I)], 0, 1)
          }
          ## for recommended cutpoints
          if(length(cutpoint_guide)==1){
            cases_long$cut_guide <- ifelse(cases_long$intstart_lag < cases_long$tcut_guide, 0, 1)
          }else if(length(cutpoint_guide) > 1){
            for(i in 1:length(cutpoint_guide)){
              # if there is only 1 cut, then it's only "tcut_fixed", if there are n cuts, its "tcut_fixed.n"
            I <- paste0(".",i)
            cases_long[,paste0("cut_guide",I)] <- ifelse(cases_long$intstart_lag < cases_long[,paste0("tcut_guide",I)], 0, 1)
            }
          }
          cases_long

          
          # return only columns for first event and number of events for each interval (if multiple events within an interval)
          # events column
          cases <- cases_long %>%
            ungroup() %>%
            mutate(
              # sum up eventnum's to reach total event# per interval
              event = rowSums(select(., starts_with("eventnum")), na.rm=T),
              # sum up cut dummy variables into one cut categorical variable
              cut_f_2 = rowSums(select(., starts_with("cut_fixed_2")), na.rm=T),
              cut_f_4 = rowSums(select(., starts_with("cut_fixed_4")), na.rm=T),
              cut_f_6 = rowSums(select(., starts_with("cut_fixed_6")), na.rm=T),
              cut_r_2 = rowSums(select(., starts_with("cut_random")), na.rm=T),
              cut_guide = rowSums(select(., starts_with("cut_guide")), na.rm=T)
            )  %>%
            # only keep entries with intlength != 0, this removes obsstart rows
            filter(intstart != 0)
          
          # 3. Generate first events for each partition
          
          cases_partitioned_fixed_2 <- partitionf(df=cases, cut_point="cut_f_2") %>%
            mutate(
              indiv_round = indiv,
              indiv = paste0(indiv,".",cut_f_2),
              # cut variable so it works with metaf function
              cut=cut_f_2
            )
          # cases_partitioned_fixed_4 <- partitionf(df=cases, cut_point="cut_f_4") %>%
          #   mutate(
          #     indiv_round = indiv,
          #     indiv = paste0(indiv,".",cut_f_4),
          #     # cut variable so it works with metaf function
          #     cut=cut_f_4
          #   )
          # cases_partitioned_fixed_6 <- partitionf(df=cases, cut_point="cut_f_6") %>%
          #   mutate(
          #     indiv_round = indiv,
          #     indiv = paste0(indiv,".",cut_f_6),
          #     # cut variable so it works with metaf function
          #     cut=cut_f_6
          #   )
          # cases_partitioned_random_2 <- partitionf(df=cases, cut_point="cut_r_2") %>%
          #   mutate(
          #     indiv_round = indiv,
          #     indiv = paste0(indiv,".",cut_r_2),
          #     # cut variable so it works with metaf function
          #     cut=cut_r_2)
          cases_partitioned_guide <- partitionf(df=cases, cut_point="cut_guide") %>%
            mutate(
              indiv_round = indiv,
              indiv = paste0(indiv,".",cut_guide),
              # cut variable so it works with metaf function
              cut=cut_guide)
          
          #-----CREATE DATA [END]-----
          
          #-----DGP [END]-----
          
          # saving results depending on whether or not we adjust for seasonal effect
          ## meta-analysis function already has an if_else statement for potential seasonal adjustment
          if(season == "n"){
            
            allevent.analysis <- tryCatch(fixest::fepois(event ~ offset(log(intlength)) + expos | as.factor(indiv), data=cases, vcov="iid", ssc=ssc(adj=F)), error=function(e){NA}) %>% suppressMessages()
            firstevent.analysis <- tryCatch(fixest::fepois(eventnum1 ~ offset(log(intlength)) + expos | as.factor(indiv), data=cases, vcov="iid", ssc=ssc(adj=F)), error=function(e){NA}) %>% suppressMessages()
                        
            time_adj_2.analysis <- tryCatch(fixest::fepois(eventnum1 ~ offset(log(intlength)) + expos + as.factor(cut_fixed_2) | as.factor(indiv), data=cases, vcov="iid", ssc=ssc(adj=F)), error=function(e){NA}) %>% suppressMessages()
            time_adj_guide.analysis <- tryCatch(fixest::fepois(eventnum1 ~ offset(log(intlength)) + expos + as.factor(cut_guide) | as.factor(indiv), data=cases, vcov="iid", ssc=ssc(adj=F)), error=function(e){NA}) %>% suppressMessages()
            
            partition2.analysis <- tryCatch(fixest::fepois(eventnum1_cut_f_2 ~ offset(log(intlength)) + expos | as.factor(indiv), data=cases_partitioned_fixed_2, cluster=~indiv_round, ssc=ssc(adj=F)), error=function(e){NA}) %>% suppressMessages()
            partitionguide.analysis <- tryCatch(fixest::fepois(eventnum1_cut_guide  ~ offset(log(intlength)) + expos | as.factor(indiv), data=cases_partitioned_guide, cluster=~indiv_round, ssc=ssc(adj=F)), error=function(e){NA}) %>% suppressMessages()
            
            # # BOOTSTRAP
            # boot.results <- c()
            # cases_boot <- cases_partitioned_guide %>% select(indiv, cut, intlength, expos, indiv_round, eventnum1_cut_guide)
            # for(k in 1:nboot){
            #   # 7/11/2022
            #   ## sample cases with replacement
            #   boot <- data.frame(indivboot = sample(1:nindiv, nindiv, replace=T))
            #   
            #   ## frequency table to df
            #   boot.freq <- boot$indivboot %>% table() %>% as.data.frame
            #   # names(boot.freq)[1] <- "indiv"
            #   # resampled.dat <- merge(cases, boot.freq, by="indiv")
            #   names(boot.freq)[1] <- "indiv_round"
            #   resampled.dat <- merge(cases_boot, boot.freq, by="indiv_round")
            #   
            #   
            #   boot.dat1 <- data.frame()
            #   
            #   ## for each frequency i of resampling
            #   for(i in unique(resampled.dat$Freq)){
            #     
            #     resampled.dat2 <- resampled.dat %>% filter(Freq==i)
            #     boot.sample.list <- replicate(i, resampled.dat2, simplify = FALSE)
            #     # change list entry numbers 
            #     for(j in 1:i){
            #       boot.sample.list[[j]]$indiv_round <- paste(boot.sample.list[[j]]$indiv_round, j, sep=".")
            #     }
            #     # collapse list to one df for that frequency number
            #     boot.sample.dat <- do.call("rbind", boot.sample.list)
            #     # bind df with frequency number into overall df
            #     boot.dat1 <- bind_rows(boot.dat1, boot.sample.dat)
            #   }
            #   boot.results[k] <- metaf(df=boot.dat1, eventvar="eventnum1_cut_guide", partitions=cutpoint_guide_num)
            # }
            
            results <- results %>%
              dplyr::add_row(
                scenario = ScenarioNumber,
                
                cond_baseline2_E.events=baseline2*ntime, cond_RIexpo=RIexpo, cond_eventdependence=eventdependence, cond_exposdist=exposdist, cond_season=season,
                
                allevent = allevent.analysis$coefficients,
                firstevent = firstevent.analysis$coefficients,
                OT_adj_2 = time_adj_2.analysis$coefficients["expos"],
                OT_adj_guide = time_adj_guide.analysis$coefficients["expos"],
                combinedpartition_fixed_2 = partition2.analysis$coefficients,
                # combinedpartition_fixed_4 = tryCatch(fixest::fepois(eventnum1_cut_f_4 ~ offset(log(intlength)) + expos | as.factor(indiv), data=cases_partitioned_fixed_4, vcov="iid", ssc=ssc(adj=F))$coefficients, error=function(e){NA}) %>% suppressMessages(),
                # combinedpartition_fixed_6 = tryCatch(fixest::fepois(eventnum1_cut_f_6 ~ offset(log(intlength)) + expos | as.factor(indiv), data=cases_partitioned_fixed_6, vcov="iid", ssc=ssc(adj=F))$coefficients, error=function(e){NA}) %>% suppressMessages(),
                # combinedpartition_random_2 = tryCatch(fixest::fepois(eventnum1_cut_r_2 ~ offset(log(intlength)) + expos | as.factor(indiv), data=cases_partitioned_random_2, vcov="iid", ssc=ssc(adj=F))$coefficients, error=function(e){NA}) %>% suppressMessages(),
                combinedpartition_guide = partitionguide.analysis$coefficients,
                
                # meta_guide = metaf(df=cases_partitioned_guide, eventvar="eventnum1_cut_guide", partitions=cutpoint_guide_num),
                
                iidse_allevent = allevent.analysis$se,
                iidse_firstevent = firstevent.analysis$se,
                iidse_OT_adj_2 = time_adj_2.analysis$se["expos"],
                iidse_OT_adj_guide = time_adj_guide.analysis$se["expos"],
                # iidse_combinedpartition_fixed_2 = tryCatch(fixest::fepois(eventnum1_cut_f_2 ~ offset(log(intlength)) + expos | as.factor(indiv), data=cases_partitioned_fixed_2, vcov="iid", ssc=ssc(adj=F))$se, error=function(e){NA}) %>% suppressMessages(),
                # iidse_combinedpartition_fixed_4 = tryCatch(fixest::fepois(eventnum1_cut_f_4 ~ offset(log(intlength)) + expos | as.factor(indiv), data=cases_partitioned_fixed_4, vcov="iid", ssc=ssc(adj=F))$se, error=function(e){NA}) %>% suppressMessages(),
                # iidse_combinedpartition_fixed_6 = tryCatch(fixest::fepois(eventnum1_cut_f_6 ~ offset(log(intlength)) + expos | as.factor(indiv), data=cases_partitioned_fixed_6, vcov="iid", ssc=ssc(adj=F))$se, error=function(e){NA}) %>% suppressMessages(),
                # iidse_combinedpartition_random_2 = tryCatch(fixest::fepois(eventnum1_cut_r_2 ~ offset(log(intlength)) + expos | as.factor(indiv), data=cases_partitioned_random_2, vcov="iid", ssc=ssc(adj=F))$se, error=function(e){NA}) %>% suppressMessages(),
                # iidse_combinedpartition_guide = tryCatch(fixest::fepois(eventnum1_cut_guide  ~ offset(log(intlength)) + expos | as.factor(indiv), data=cases_partitioned_guide, vcov="iid", ssc=ssc(adj=F))$se, error=function(e){NA}) %>% suppressMessages(),
                
                # clusterse_allevent = tryCatch(fixest::fepois(event ~ offset(log(intlength)) + expos | as.factor(indiv), data=cases, cluster=~indiv, ssc=ssc(adj=F))$se, error=function(e){NA}) %>% suppressMessages(),
                # clusterse_firstevent = tryCatch(fixest::fepois(eventnum1 ~ offset(log(intlength)) + expos | as.factor(indiv), data=cases, cluster=~indiv, ssc=ssc(adj=F))$se, error=function(e){NA}) %>% suppressMessages(),
                clusterse_combinedpartition_fixed_2 = partition2.analysis$se,
                # clusterse_combinedpartition_fixed_4 = tryCatch(fixest::fepois(eventnum1_cut_f_4 ~ offset(log(intlength)) + expos | as.factor(indiv), data=cases_partitioned_fixed_4, cluster=~indiv_round, ssc=ssc(adj=F))$se, error=function(e){NA}) %>% suppressMessages(),
                # clusterse_combinedpartition_fixed_6 = tryCatch(fixest::fepois(eventnum1_cut_f_6 ~ offset(log(intlength)) + expos | as.factor(indiv), data=cases_partitioned_fixed_6, cluster=~indiv_round, ssc=ssc(adj=F))$se, error=function(e){NA}) %>% suppressMessages(),
                # clusterse_combinedpartition_random_2 = tryCatch(fixest::fepois(eventnum1_cut_r_2 ~ offset(log(intlength)) + expos | as.factor(indiv), data=cases_partitioned_random_2, cluster=~indiv_round, ssc=ssc(adj=F))$se, error=function(e){NA}) %>% suppressMessages(),
                clusterse_combinedpartition_guide = partitionguide.analysis$se
                # bootstrapse_meta_guide = sd(boot.results)
              )
          }else if(season == "y"){
            
            allevent.analysis <- tryCatch(fixest::fepois(event ~ offset(log(intlength)) + expos + season | as.factor(indiv), data=cases, vcov="iid", ssc=ssc(adj=F)), error=function(e){NA}) %>% suppressMessages()
            firstevent.analysis <- tryCatch(fixest::fepois(eventnum1 ~ offset(log(intlength)) + expos + season | as.factor(indiv), data=cases, vcov="iid", ssc=ssc(adj=F)), error=function(e){NA}) %>% suppressMessages()
                        
            OT_adj_2.analysis <- tryCatch(fixest::fepois(eventnum1 ~ offset(log(intlength)) + expos + as.factor(cut_fixed_2) + season  | as.factor(indiv), data=cases, vcov="iid", ssc=ssc(adj=F)), error=function(e){NA}) %>% suppressMessages()
            OT_adj_guide.analysis <- tryCatch(fixest::fepois(eventnum1 ~ offset(log(intlength)) + expos + as.factor(cut_guide) + season  | as.factor(indiv), data=cases, vcov="iid", ssc=ssc(adj=F)), error=function(e){NA}) %>% suppressMessages()
            
            partition2.analysis <- tryCatch(fixest::fepois(eventnum1_cut_f_2 ~ offset(log(intlength)) + expos + season | as.factor(indiv), data=cases_partitioned_fixed_2, cluster=~indiv_round, ssc=ssc(adj=F)), error=function(e){NA}) %>% suppressMessages()
            partitionguide.analysis <- tryCatch(fixest::fepois(eventnum1_cut_guide  ~ offset(log(intlength)) + expos + season | as.factor(indiv), data=cases_partitioned_guide, cluster=~indiv_round, ssc=ssc(adj=F)), error=function(e){NA}) %>% suppressMessages()
            
            # # Bootstrap
            # boot.results <- c()
            # cases_boot <- cases_partitioned_guide %>% select(indiv, cut, intlength, expos, indiv_round, eventnum1_cut_guide, season)
            # for(k in 1:nboot){
            #   # 7/11/2022
            #   ## sample cases with replacement
            #   boot <- data.frame(indivboot = sample(1:nindiv, nindiv, replace=T))
            #   
            #   ## frequency table to df
            #   boot.freq <- boot$indivboot %>% table() %>% as.data.frame
            #   # names(boot.freq)[1] <- "indiv"
            #   # resampled.dat <- merge(cases, boot.freq, by="indiv")
            #   names(boot.freq)[1] <- "indiv_round"
            #   resampled.dat <- merge(cases_boot, boot.freq, by="indiv_round")
            #   
            #   
            #   boot.dat1 <- data.frame()
            #   
            #   ## for each frequency i of resampling
            #   for(i in unique(resampled.dat$Freq)){
            #     
            #     resampled.dat2 <- resampled.dat %>% filter(Freq==i)
            #     boot.sample.list <- replicate(i, resampled.dat2, simplify = FALSE)
            #     # change list entry numbers 
            #     for(j in 1:i){
            #       boot.sample.list[[j]]$indiv_round <- paste(boot.sample.list[[j]]$indiv_round, j, sep=".")
            #     }
            #     # collapse list to one df for that frequency number
            #     boot.sample.dat <- do.call("rbind", boot.sample.list)
            #     # bind df with frequency number into overall df
            #     boot.dat1 <- bind_rows(boot.dat1, boot.sample.dat)
            #   }
            #   boot.results[k] <- metaf(df=boot.dat1, eventvar="eventnum1_cut_guide", partitions=cutpoint_guide_num)
            # }
            
            results <- results %>%
              dplyr::add_row(
                scenario = ScenarioNumber,
                
                cond_baseline2_E.events=baseline2*ntime, cond_RIexpo=RIexpo, cond_eventdependence=eventdependence, cond_exposdist=exposdist, cond_season=season,
                
                
                allevent = allevent.analysis$coefficients["expos"],
                firstevent = firstevent.analysis$coefficients["expos"],
                OT_adj_2 = time_adj_2.analysis$coefficients["expos"],
                OT_adj_guide = time_adj_guide.analysis$coefficients["expos"],
                combinedpartition_fixed_2 = partition2.analysis$coefficients["expos"],
                combinedpartition_guide = partitionguide.analysis$coefficients["expos"],

                iidse_allevent = allevent.analysis$se["expos"],
                iidse_firstevent = firstevent.analysis$se["expos"],
                iidse_OT_adj_2 = time_adj_2.analysis$se["expos"],
                iidse_OT_adj_guide = time_adj_guide.analysis$se["expos"],
                clusterse_combinedpartition_fixed_2 = partition2.analysis$se["expos"],
                clusterse_combinedpartition_guide = partitionguide.analysis$se["expos"]

                # allevent = tryCatch(fixest::fepois(event ~ offset(log(intlength)) + expos + season | as.factor(indiv), data=cases, vcov="iid", ssc=ssc(adj=F))$coefficients["expos"], error=function(e){NA}) %>% suppressMessages(),
                # firstevent = tryCatch(fixest::fepois(eventnum1 ~ offset(log(intlength)) + expos + season | as.factor(indiv), data=cases, vcov="iid", ssc=ssc(adj=F))$coefficients["expos"], error=function(e){NA}) %>% suppressMessages(),
                # combinedpartition_fixed_2 = tryCatch(fixest::fepois(eventnum1_cut_f_2 ~ offset(log(intlength)) + expos + season | as.factor(indiv), data=cases_partitioned_fixed_2, cluster=~indiv_round, ssc=ssc(adj=F))$coefficients["expos"], error=function(e){NA}) %>% suppressMessages(),
                # combinedpartition_fixed_4 = tryCatch(fixest::fepois(eventnum1_cut_f_4 ~ offset(log(intlength)) + expos + season | as.factor(indiv), data=cases_partitioned_fixed_4, cluster=~indiv_round, ssc=ssc(adj=F))$coefficients["expos"], error=function(e){NA}) %>% suppressMessages(),
                # combinedpartition_fixed_6 = tryCatch(fixest::fepois(eventnum1_cut_f_6 ~ offset(log(intlength)) + expos + season | as.factor(indiv), data=cases_partitioned_fixed_6, cluster=~indiv_round, ssc=ssc(adj=F))$coefficients["expos"], error=function(e){NA}) %>% suppressMessages(),
                # combinedpartition_random_2 = tryCatch(fixest::fepois(eventnum1_cut_r_2 ~ offset(log(intlength)) + expos + season | as.factor(indiv), data=cases_partitioned_random_2, cluster=~indiv_round, ssc=ssc(adj=F))$coefficients["expos"], error=function(e){NA}) %>% suppressMessages(),
                # combinedpartition_guide = tryCatch(fixest::fepois(eventnum1_cut_guide ~ offset(log(intlength)) + expos + season | as.factor(indiv), data=cases_partitioned_guide, cluster=~indiv_round, ssc=ssc(adj=F))$coefficients["expos"], error=function(e){NA}) %>% suppressMessages(),
                # 
                # meta_guide = metaf(df=cases_partitioned_guide, eventvar="eventnum1_cut_guide", partitions=cutpoint_guide_num),
                # 
                # iidse_allevent = tryCatch(fixest::fepois(event ~ offset(log(intlength)) + expos + season | as.factor(indiv), data=cases, vcov="iid", ssc=ssc(adj=F))$se["expos"], error=function(e){NA}) %>% suppressMessages(),
                # iidse_firstevent = tryCatch(fixest::fepois(eventnum1 ~ offset(log(intlength)) + expos + season | as.factor(indiv), data=cases, vcov="iid", ssc=ssc(adj=F))$se["expos"], error=function(e){NA}) %>% suppressMessages(),
                # iidse_combinedpartition_fixed_2 = tryCatch(fixest::fepois(eventnum1_cut_f_2 ~ offset(log(intlength)) + expos + season | as.factor(indiv), data=cases_partitioned_fixed_2, vcov="iid", ssc=ssc(adj=F))$se["expos"], error=function(e){NA}) %>% suppressMessages(),
                # iidse_combinedpartition_fixed_4 = tryCatch(fixest::fepois(eventnum1_cut_f_4 ~ offset(log(intlength)) + expos + season | as.factor(indiv), data=cases_partitioned_fixed_4, vcov="iid", ssc=ssc(adj=F))$se["expos"], error=function(e){NA}) %>% suppressMessages(),
                # iidse_combinedpartition_fixed_6 = tryCatch(fixest::fepois(eventnum1_cut_f_6 ~ offset(log(intlength)) + expos + season | as.factor(indiv), data=cases_partitioned_fixed_6, vcov="iid", ssc=ssc(adj=F))$se["expos"], error=function(e){NA}) %>% suppressMessages(),
                # iidse_combinedpartition_random_2 = tryCatch(fixest::fepois(eventnum1_cut_r_2 ~ offset(log(intlength)) + expos + season | as.factor(indiv), data=cases_partitioned_random_2, vcov="iid", ssc=ssc(adj=F))$se["expos"], error=function(e){NA}) %>% suppressMessages(),
                # iidse_combinedpartition_guide = tryCatch(fixest::fepois(eventnum1_cut_guide ~ offset(log(intlength)) + expos + season | as.factor(indiv), data=cases_partitioned_guide, vcov="iid", ssc=ssc(adj=F))$se["expos"], error=function(e){NA}) %>% suppressMessages(),
                # 
                # clusterse_allevent = tryCatch(fixest::fepois(event ~ offset(log(intlength)) + expos + season | as.factor(indiv), data=cases, cluster=~indiv, ssc=ssc(adj=F))$se["expos"], error=function(e){NA}) %>% suppressMessages(),
                # clusterse_firstevent = tryCatch(fixest::fepois(eventnum1 ~ offset(log(intlength)) + expos + season | as.factor(indiv), data=cases, cluster=~indiv, ssc=ssc(adj=F))$se["expos"], error=function(e){NA}) %>% suppressMessages(),
                # clusterse_combinedpartition_fixed_2 = tryCatch(fixest::fepois(eventnum1_cut_f_2 ~ offset(log(intlength)) + expos + season | as.factor(indiv), data=cases_partitioned_fixed_2, cluster=~indiv_round, ssc=ssc(adj=F))$se["expos"], error=function(e){NA}) %>% suppressMessages(),
                # clusterse_combinedpartition_fixed_4 = tryCatch(fixest::fepois(eventnum1_cut_f_4 ~ offset(log(intlength)) + expos + season | as.factor(indiv), data=cases_partitioned_fixed_4, cluster=~indiv_round, ssc=ssc(adj=F))$se["expos"], error=function(e){NA}) %>% suppressMessages(),
                # clusterse_combinedpartition_fixed_6 = tryCatch(fixest::fepois(eventnum1_cut_f_6 ~ offset(log(intlength)) + expos + season | as.factor(indiv), data=cases_partitioned_fixed_6, cluster=~indiv_round, ssc=ssc(adj=F))$se["expos"], error=function(e){NA}) %>% suppressMessages(),
                # clusterse_combinedpartition_random_2 = tryCatch(fixest::fepois(eventnum1_cut_r_2 ~ offset(log(intlength)) + expos + season | as.factor(indiv), data=cases_partitioned_random_2, cluster=~indiv_round, ssc=ssc(adj=F))$se["expos"], error=function(e){NA}) %>% suppressMessages(),
                # clusterse_combinedpartition_guide = tryCatch(fixest::fepois(eventnum1_cut_guide ~ offset(log(intlength)) + expos + season | as.factor(indiv), data=cases_partitioned_guide, cluster=~indiv_round, ssc=ssc(adj=F))$se["expos"], error=function(e){NA}) %>% suppressMessages(),
                # 
                # bootstrapse_meta_guide = sd(boot.results)
              )
          }
          
          print(paste(nrow(results), f, sep="_"))
          # export
          write.csv(cases_wide, paste0("Simulated Data Raw/", "cases_wide", "_Scenario", ScenarioNumber,"_Rep", f,".csv"), row.names = FALSE)
        }
      }
    }
  }
}
Sys.time()-start.time

results
# # Export CSV
write.csv(results, paste0("Simulated Data Results/", "results_Scenario", ScenarioNumber, ".csv"), row.names = FALSE)

# # Import CSV
# results1 <- read.csv("C:/Users/kenny/OneDrive/Professional/#Education/Duke-NUS PhD/Thesis/Partitioned SCCS Notes/R/Tests/R Results/Results_Seasonsn_Sims20_Date8_9.csv")
# results2 <- read.csv("C:/Users/kenny/OneDrive/Professional/#Education/Duke-NUS PhD/Thesis/Partitioned SCCS Notes/R/Tests/R Results/Results_Seasonsy_Sims20_Date8_9.csv")
# # bind results from example 1 (season = y) and example 2 (season = n)
# results <- rbind(results1, results2)

```

